# postgres
spring:
  jpa:
    generate-ddl: "true"
    database: oracle
    properties:
      hibernate:
        format_sql: "true"
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: "true"
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/jhelperpdb
    username: jhelperown
    password: 
    hikari:
      connection-timeout: "30000"
      idle-timeout: "300000"
      maximum-pool-size: "10"
      max-lifetime: "1800000"
      minimum-idle: "5"
