logging:
  file:
    path: c:/work/logs/
    name: c:/work/logs/app.log
  level:
    web: debug
    org:
      springframework:
        data:
          elasticsearch:
            core: debug
      docx4j: error
    root: debug