# lucene
spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: "lucene"
            directory:
              type: local-filesystem
              root: c:\\tmp\\jhelper-index
