server:
  port: "9080"

# sqlite
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    jdbc-url: jdbc:sqlite:data/jhelper.db
    username: ""
    password: ""
  servlet:
    multipart:
      enabled: "true"
