jhelper:
  file-browser:
    rootPath: "/work"
    trashPath: "/tmp/jhelper/trash"
    board:
      exclusions:
        - "*.exe"
        - "*.msi"
        - "*.zip"
        - "*.tar"
        - "*.gzip"
    searchMode: "search"
  board:
    searchMode: "db"
  search:
    indexingOnLoad: "true"

