server:
  port: "9080"

spring:
  config:
    import:
      - classpath:/application-postgres.yml
      - classpath:/application-jhelper.yml
      - classpath:/application-log.yml
      - classpath:/application-search.yml
      #- classpath:/application-elastic.yml
  servlet:
    multipart:
      enabled: "true"

