# lucene
spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: "lucene"
            directory:
              type: local-filesystem
              root: /tmp/jhelper-index
            analysis:
              configurer: class:com.jhelper.jserve.config.SearchAnalysisConfigurer