server:
  port: "9080"

spring:
  config:
    import:
      - classpath:/application-postgres.yaml
      - classpath:/application-jhelper.yaml
      - classpath:/application-log.yaml
      - classpath:/application-search.yaml
      #- classpath:/application-elastic.yaml
  servlet:
    multipart:
      enabled: "true"

