# postgres
spring:
  jpa:
    generate-ddl: "true"
    database: postgresql
    properties:
      hibernate:
        format_sql: "true"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: "true"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jHelper
    username: root
    password: whdaks1!
    hikari:
      connection-timeout: "30000"
      idle-timeout: "300000"
      maximum-pool-size: "10"
      max-lifetime: "1800000"
      minimum-idle: "5"
